### ISSUE TITLE
Export static page

### ISSUE THREAD

**Issue by bonndan** [issaafalkattan/react-landing-page-template-2021#4]
I would like to export a static page to use with GitHub pages. `build-prod` produces something in the `out` directory, but an index.html file is missing. What do I have to do? I've already tried to add an export path map in next config, but to no sucess (module missing, 404 pages are generated containing the content, however).

Any advice?

**Comment by issaafalkattan** [comment]
This should be fixed now! Thanks for reporting! 

For context, the issue was with how the pages folder was structured, it was missing a few files that are essential for next.js to map the correct routes in the build! 

Will close for now, but please reopen the issue if the fix was not sufficient 😄 !
